apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGateway
metadata:
  name: wfd14
  namespace: default
spec:
  service:
    type: ClusterIP
  api:
    title: Where For Dinner API Gateway
    description: Where For Dinner APIs for creating searches and retrieving search results.
    version: 1.0.0
  env:
  - name: spring.cloud.gateway.httpclient.connect-timeout
    value: "90"
