apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: where-for-dinner-ingress
  namespace: default
spec:
  virtualhost:
    fqdn: where-for-dinner.a4.fynesy.com
  routes:
  - conditions:
    - prefix: /
    services:
    - name: wfd14
      port: 80
